version: "3"

services:
  mc:
    image: itzg/minecraft-server:java8
    ports:
      - 25565:25565
    tty: true
    stdin_open: true
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

    environment:
      # General options
      EXTRA_ARGS: "@java9args.txt -Dfml.readTimeout=180"
      # Server options
      TYPE: "FORGE"
      EULA: "TRUE"
      VERSION: 1.7.10
      MOTD: ${MOTD}
      ICON: ${ICON}
      OVERRIDE_ICON: true
      # Rcon 
      RCON_PASSWORD: ${RCON_PASSWORD}
      # Pack options
      GENERIC_PACK: "https://downloads.gtnewhorizons.com/ServerPacks/GT_New_Horizons_2.5.1_Server_Java_8.zip"
      FORGE_VERSION: "10.13.4.1614"
      SKIP_GENERIC_PACK_UPDATE_CHECK: true
      USE_MODPACK_START_SCRIPT: "false"

    volumes:
      - ./data:/data   

  mc-backup:
    image: itzg/mc-backup
    depends_on:
      mc:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: mc
      # since this service waits for mc to be healthy, no initial delay is needed
      INITIAL_DELAY: 0
    volumes:
      - ./data:/data:ro
      - ./backups:/backups